### ISSUE TITLE
Error related to xarray?

### ISSUE THREAD

**Issue by goldford** [OceanParcels/parcels#1082]
Hi there, 
I'm running a tutorial example and encountering the following error. Can you help me interpret it? I tried updating xarray but didn't seem to change anything.

code: 
```
data_path = '/project/6006412/ccccc/nemo_results/dddd/CDF/1979/'
mesh_path = '/project/6006412/ccccc/data/mesh_mask/'
coord_path = '/project/6006412/ccccc/data/grid/'
ufiles = sorted(glob(data_path+'dddd-RUN200_1h_grid_U_2D*.nc'))
vfiles = sorted(glob(data_path+'dddd-RUN200_1h_grid_V_2D*.nc'))
wfiles = sorted(glob(data_path+'dddd-RUN200_1h_grid_W*.nc'))

#mesh_mask = coord_path + 'coordinates_dddd_1500m.nc'
mesh_mask = mesh_path + 'mesh_mask_20210406.nc'

print("Check length of ufiles: " + str(len(ufiles)))

filenames = {'U': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': wfiles[0], 'data': ufiles},
             'V': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': wfiles[0], 'data': vfiles},
             'W': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': wfiles[0], 'data': wfiles}}

variables = {'U': 'uo',
             'V': 'vo',
             'W': 'wo'}
dimensions = {'U': {'lon': 'glamf', 'lat': 'gphif', 'depth': 'depthw', 'time': 'time_counter'},
              'V': {'lon': 'glamf', 'lat': 'gphif', 'depth': 'depthw', 'time': 'time_counter'},
              'W': {'lon': 'glamf', 'lat': 'gphif', 'depth': 'depthw', 'time': 'time_counter'}}

fieldset = FieldSet.from_nemo(filenames, variables, dimensions)

#pset = ParticleSet.from_line(fieldset=fieldset, pclass=JITParticle,
#                             size=10,
#                             start=(1.9, 52.5),
#                             finish=(3.4, 51.6),
#                             depth=1)

pset = ParticleSet(fieldset=fieldset,
                   pclass=JITParticle, 
                   lon=-123.216, 
                   lat=49.122,
                   depth=1)

# 3. Execute the advection kernel on fieldset
output_file = pset.ParticleFile(name="GCParticles.nc", outputdt=3600)

kernels = pset.Kernel(AdvectionRK4_3D)
pset.execute(kernels,
             runtime=delta(days=4),   # total length of the run
             dt=delta(hours=6))       # kernel timestep
`
```
**error**
```
`(py3-8-10_Jul9) [cccccc@gra-login1 parcels_tests]$ python basic_2d_test.py -j 1
Check length of ufiles: 365
sh: None: command not found
INFO: Compiled ArrayJITParticleAdvectionRK4_3D ==> /tmp/parcels-3106043/libea98afdbdbac9a9042b5ed968bdf1628_0.so
Traceback (most recent call last):
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/xarray/core/dataset.py", line 1398, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'uo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basic_2d_test.py", line 56, in <module>
    pset.execute(kernels,
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/particleset/baseparticleset.py", line 433, in execute
    next_input = self.fieldset.computeTimeChunk(time, np.sign(dt)) if self.fieldset is not None else np.inf
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/fieldset.py", line 1072, in computeTimeChunk
    data = f.computeTimeChunk(data, tind)
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/field.py", line 1375, in computeTimeChunk
    buffer_data = filebuffer.data
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/fieldfilebuffer.py", line 159, in data
    return self.data_access()
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/fieldfilebuffer.py", line 162, in data_access
    data = self.dataset[self.name]
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/xarray/core/dataset.py", line 1502, in __getitem__
    return self._construct_dataarray(key)
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/xarray/core/dataset.py", line 1400, in _construct_dataarray
    _, name, variable = _get_virtual_variable(
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/xarray/core/dataset.py", line 173, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'uo'
Exception ignored in: <function ParticleFileSOA.__del__ at 0x2b070030ef70>
Traceback (most recent call last):
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/particlefile/particlefilesoa.py", line 40, in __del__
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/particlefile/baseparticlefile.py", line 235, in __del__
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/particlefile/baseparticlefile.py", line 240, in close
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/parcels/particlefile/particlefilesoa.py", line 125, in export
  File "/project/6006412/cccccc/py3-8-10_Jul9/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
FileNotFoundError: [Errno 2] No such file or directory: 'out-KXUEJNGD/0/pset_info.npy'
`
```

**Comment by erikvansebille** [comment]
Hi @goldford. The relevant error seems to be `KeyError: 'uo'`. Are you sure that the zonal velocity field in the netcdf file is called `uo`? If not, you should adapt your `variables` dictionary

**Comment by goldford** [comment]
that's exactly it.
