### ISSUE TITLE
Time interpolation breaks if one tracer file goes missing

### ISSUE THREAD

**Issue by daanreijnders** [OceanParcels/parcels#1308]
I am running a 3D simulation using NEMO fields, in which I also sample temperature and salinity. One of my temperature files was corrupt and causes Parcels to break, so I removed it. However, this still causes Parcels to break, giving the following traceback:

```
Traceback (most recent call last):
  File "/storage/home/4302001/tracer_backtracking/simulations/NA_simulations_MEDUSA_debug_interpolation_300_depth_release.py", line 266, in <module>
    pset.execute(parcels.AdvectionRK4_3D + pset.Kernel(EDW_Sampler_debug.EDW_Sampler), 
  File "/storage/home/4302001/sources/parcels/parcels/particleset/baseparticleset.py", line 505, in execute
    next_input = self.fieldset.computeTimeChunk(time, dt)
  File "/storage/home/4302001/sources/parcels/parcels/fieldset.py", line 1052, in computeTimeChunk
    raise TimeExtrapolationError(time, field=f, msg='In fset.computeTimeChunk')
parcels.tools.statuscodes.TimeExtrapolationError: U sampled outside time domain at time 2006-01-03T12:00:00.000000000.In fset.computeTimeChunk Try setting allow_time_extrapolation to True
```

Parcels seems to have issues if the velocity fields for a timestep exist, while the tracer fields don't.

If I also remove the velocity files, Parcels runs as expected, since in principle it should be able to deal with irregular timesteps.

Possible hint: Perhaps this issue is related to all files being loaded together using `parcels.FieldSet.from_nemo()`, rather than the temperature files being added later. I've worked with tracer fields that have a different timestep before and for that I added the fields after the initial `FieldSet` was made.

**Comment by erikvansebille** [comment]
This will likely be fixed in v4 with the new Interpolators
