### ISSUE TITLE
"OSError: could not get source code" for "k_WestVel = pset.Kernel(WestVel)" command in tutorial

### ISSUE THREAD

**Issue by chnrr1** [OceanParcels/parcels#1310]
When I tried to follow the tutorial of parcels in python shell in ubuntu 20.04, I got this error:

```
`$k_WestVel = pset.Kernel(WestVel)

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/.../py3_parcels_mpi/lib/python3.10/site-packages/parcels/particleset/particlesetsoa.py", line 639, in Kernel
    return Kernel(self.fieldset, self.collection.ptype, pyfunc=pyfunc, c_include=c_include,

  File "/.../py3_parcels_mpi/lib/python3.10/site-packages/parcels/kernel/kernelsoa.py", line 58, in __init__
    self.funccode = funccode or inspect.getsource(pyfunc.__code__)

  File "/.../py3_parcels_mpi/lib/python3.10/inspect.py", line 1147, in getsource
    lines, lnum = getsourcelines(object)

  File "/.../py3_parcels_mpi/lib/python3.10/inspect.py", line 1129, in getsourcelines
    lines, lnum = findsource(object)

  File "/.../py3_parcels_mpi/lib/python3.10/inspect.py", line 958, in findsource
    raise OSError('could not get source code')

OSError: could not get source code`

```
I found these on google:

https://stackoverflow.com/questions/57035364/inspect-getsourcelinesobject-shows-oserror-if-run-from-python-shell-but-gives

https://github.com/HunterMcGushion/hyperparameter_hunter/issues/191

in which they believed that the "inspect.getsource(...)" function is not working in the interactive mode of python. So I wonder if this is the issue and how to solve it, like making a script instead?

**Comment by erikvansebille** [comment]
This does not appear to be an Issue with Parcels, but rather with (your installation) of python? Can you try this in a script, indeed?
