### ISSUE TITLE
Issue running oceanparcels on updated environment

### ISSUE THREAD

**Issue by hadarberman1** [OceanParcels/parcels#1390]
Hi everyone,

I have a bug. The same code I run (with ROMS grid) works for an older version of my environment that uses python 3.10.8, however the same code fails with an updated environment using python 3.11.3. The error I get on the updated environment is:

Traceback (most recent call last):
  File "/Users/hadarberman/miniconda3/envs/py3_parcels_mpi/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c2555acd0489>", line 1, in <module>
    runfile('/Users/hadarberman/PycharmProjects/pythonProject1/med_coords.py', wdir='/Users/hadarberman/PycharmProjects/pythonProject1')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/hadarberman/PycharmProjects/pythonProject1/med_coords.py", line 54, in <module>
    pset.execute(AdvectionRK4, runtime=delta(seconds=100),
  File "/Users/hadarberman/miniconda3/envs/py3_parcels_mpi/lib/python3.11/site-packages/parcels/particleset/baseparticleset.py", line 427, in execute
    next_input = self.fieldset.computeTimeChunk(time, np.sign(dt)) if self.fieldset is not None else np.inf
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hadarberman/miniconda3/envs/py3_parcels_mpi/lib/python3.11/site-packages/parcels/fieldset.py", line 1052, in computeTimeChunk
    data = f.computeTimeChunk(data, tind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hadarberman/miniconda3/envs/py3_parcels_mpi/lib/python3.11/site-packages/parcels/field.py", line 1412, in computeTimeChunk
    data = self.data_concatenate(data, buffer_data, tindex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hadarberman/miniconda3/envs/py3_parcels_mpi/lib/python3.11/site-packages/parcels/field.py", line 1371, in data_concatenate
    data = lib.concatenate([data_to_concat, data[tindex+1:, :]], axis=0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 2174 and the array at index 1 has size 2173

This is my code:

from parcels import FieldSet, ParticleSet, JITParticle
from parcels import AdvectionRK4, ErrorCode
import numpy as np
import netCDF4 as nc
from datetime import timedelta as delta
import matplotlib.pyplot as plt
import math
import os
import sys

filedir = './'
zslice  = filedir + 'z_EMed300m_his.00000.nc'
zslice0 = filedir + 'z_EMed300m_his.00000.nc'

grd = './EMed300m_grd.nc'

filenames = {'U': {'lon': grd, 'lat': grd, 'depth': zslice0, 'data': zslice},
        'V': {'lon': grd, 'lat': grd, 'depth': zslice0, 'data': zslice}}

variables = {'U': 'u', 'V': 'v'}

dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth', 'time': 'time'},
              'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth', 'time': 'time'}}

indices = {'depth' : [0]}
fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions, indices)

#release particles in the boundary current
lats1d = np.linspace(31.25, 31.75, num=100)
lons1d = np.linspace(32.75, 33.25, num=100)

[lons, lats] = np.meshgrid(lons1d, lats1d)

nstart = 0
nend   = 1
nskip  = 0
ncycle = nend-nstart+nskip-1
print('ncycle: ', ncycle)

pset=ParticleSet(fieldset, JITParticle, lon=lons, lat=lats)
#pset.show(field=fieldset.U)

def DeleteParticle(particle, fieldset, time):
    particle.delete()

output_file = pset.ParticleFile(name='prt_data_offshore30km1.zarr', outputdt=delta(seconds=2))
pset.execute(AdvectionRK4, runtime=delta(seconds=100),
             dt=delta(seconds=2), output_file=output_file,
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})

The code runs fine for the old environment.. 
Thanks for your help,
Hadar.

**Comment by erikvansebille** [comment]
Thanks for reporting @hadarberman1. I had a read through the error message, and at first glance it seems quite straightforward: at least one of the timeslices in `zslice` in your datasets has a different size than the others. The surprising thing is that this did not throw an error in python 3.10.8...

Could you check whether all of your time slices are the same? Can you see why one has 2174 grid cells, and another has 2173?

**Comment by hadarberman1** [comment]
Hi Erik! Thanks for your quick reply.

All my files in zslice are the same size. Further, in the current run I am only reading this one file.
These are the dimensions of the zslice files:
netcdf z_EMed300m_his.00000 {
dimensions:
	xi_rho = 1600 ;
	xi_u = 1599 ;
	eta_rho = 2174 ;
	eta_v = 2173 ;
	depth = 7 ;
	time = UNLIMITED ; // (4 currently)

ROMS uses a c-grid so the dimensions of u and v are different. Did I not deal with that correctly? the grid file dimensions are: 
netcdf EMed300m_grd {
dimensions:
	xi_u = 1599 ;
	eta_u = 2174 ;
	xi_v = 1600 ;
	eta_v = 2173 ;
	xi_rho = 1600 ;
	eta_rho = 2174 ;
	xi_psi = 1599 ;
	eta_psi = 2173 ;
	one = 1 ;
	two = 2 ;
	four = 4 ;
	bath = 1 ;

What I did find out while debugging is that buffer_data in field.py reads new data with the wrong dimensions (in the newer environment). In the older environment, this section of code is not accessed for some reason.

Thanks again for your assistance,
Hadar.

**Comment by erikvansebille** [comment]
Hmm, I've never used ROMS myself; but if ROMS is on a C-grid you probably need to use the `rho` points for `lon`, `lat` etc. See also the tutorial at https://docs.oceanparcels.org/en/latest/examples/tutorial_nemo_curvilinear.html (where these points are called the 'f-nodes') and the paper at https://www.geosci-model-dev.net/12/3571/2019/gmd-12-3571-2019.html

**Comment by hadarberman1** [comment]
Hi Erik, Thanks again for your reply.

I have tried using rho points and this still doesn't work. Could the problem result from the velocities being read as deferred variables? The older version reads U and V in fieldset without deferring.

**Comment by erikvansebille** [comment]
OK, in that case you could perhaps use the following code, to not use deferred_load?
```python
fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions, indices, deferred_load=False)
```

**Comment by hadarberman1** [comment]
Hi again Erik,

Your suggestion worked for loading without deferred variables. However, unfortunately, that wasn't the issue as I presumed. I now found that in the newer version, indices in field.py stay only depth indices (as specified by me: indices = {'depth' : [0]}) while in the older version indices are bound between two lon and lat in filebuffer: {'depth': [0], 'lat': range(0, 2173), 'lon': range(0, 1599)} even though I did not specify this. 

Why is the newer version not bounding my indices as not to read the whole u and v files, since their dimensions are different from the f-nodes, or in my case lon_psi/lat_psi?

Thanks again,
Hadar.

**Comment by hadarberman1** [comment]
Hi Erik,

I specified my lon and lat indices now manually, and the code runs on the new environment without an error. However, I am not sure that this is correct in terms of the grid interpolation. Can you share any advice on this matter?

Thanks again,
Hadar.
