### ISSUE TITLE
Error with Compiler

### ISSUE THREAD

**Issue by michellemho** [OceanParcels/parcels#332]
Hi Ocean Parcels team!

David Lindo-Atichati (@dlindo) has been running into an error when trying to execute a run of particles using the Brownian Motion 2D kernel. I have not been able to replicate the error on my machine, so I suspect there might be a problem with our different operating systems and some Parcels dependencies. Any advice? Thank you!

**Code:**
```
# Single lat_long
lat = [27.952]
lon = [178.991]

# number of times to repeat the particles
npart = 5

# Set random seed
random.seed(123456)

days = 50
runtime = timedelta(days=days)

random.seed(1234)
pset = ParticleSet(fieldset=fieldset, pclass=JITParticle,
                  lon=np.tile(lon,npart), lat=np.tile(lat,npart))
pset.execute(pset.Kernel(BrownianMotion2D),
            runtime=runtime,
            dt=timedelta(hours=1),
            recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
            output_file=pset.ParticleFile(name=“{}Drifters_Brownian_npart{}_{}_days”.format(len(lat),npart,days),
                                          outputdt=timedelta(hours=1)))
```

**And the error:**
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-5a75059c49ce> in <module>()
    19              dt=timedelta(hours=1),
    20              recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
---> 21              output_file=pset.ParticleFile(name=“{}Drifters_Brownian_npart{}_{}_days”.format(len(lat),npart,days), outputdt=timedelta(hours=1)))

/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/particleset.pyc in execute(self, pyfunc, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field)
   262             if self.ptype.uses_jit:
   263                 self.kernel.remove_lib()
--> 264                 self.kernel.compile(compiler=GNUCompiler())
   265                 self.kernel.load_lib()
   266

/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/kernel.pyc in compile(self, compiler)
   155         with open(self.src_file, ‘w’) as f:
   156             f.write(self.ccode)
--> 157         compiler.compile(self.src_file, self.lib_file, self.log_file)
   158         logger.info(“Compiled %s ==> %s” % (self.name, self.lib_file))
   159

/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/compiler.pyc in compile(self, src, obj, log)
    57
    58 Log output: %s”“” % (” “.join(cc), src, logfile.name, logfile2.read())
---> 59                 raise RuntimeError(err)
    60
    61

RuntimeError: Error during compilation:
Compilation command: x86_64-apple-darwin13.4.0-clang -Wall -fPIC -I/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/include -g -O3 -m64 -o /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/bd7a64720f74c5fc423c2aec69c5015b.so /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/bd7a64720f74c5fc423c2aec69c5015b.c -shared -m64
Source file: /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/bd7a64720f74c5fc423c2aec69c5015b.c
Log file: /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/bd7a64720f74c5fc423c2aec69c5015b.log

Log output: ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
 “___stack_chk_fail”, referenced from:
     _search_indices_vertical_s in bd7a64720f74c5fc423c2aec69c5015b-078936.o
 “___stack_chk_guard”, referenced from:
     _search_indices_vertical_s in bd7a64720f74c5fc423c2aec69c5015b-078936.o
 “_cos”, referenced from:
     _particle_loop in bd7a64720f74c5fc423c2aec69c5015b-078936.o
 “_floor”, referenced from:
     _search_time_index in bd7a64720f74c5fc423c2aec69c5015b-078936.o
 “_printf”, referenced from:
     _search_indices in bd7a64720f74c5fc423c2aec69c5015b-078936.o
 “_puts”, referenced from:
     _temporal_interpolation in bd7a64720f74c5fc423c2aec69c5015b-078936.o
     _search_indices in bd7a64720f74c5fc423c2aec69c5015b-078936.o
 “_rand”, referenced from:
     _particle_loop in bd7a64720f74c5fc423c2aec69c5015b-078936.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**David's OS:** 
macOS High Sierra 10.13.3 (17D102)

**My OS (no error, unable to replicate):**
OS X El Capitan 10.11.16 (15G18013)

**Parcels version:**
1.0.1

**Comment by michellemho** [comment]
Tried with another example from the parcels examples:

```
$ python example_peninsula.py --fieldset 100 100
INFO: Generating NEMO FieldSet output with basename: peninsula
Peninsula: Advecting 20 particles for 1 day, 0:00:00

Traceback (most recent call last):
  File "/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/compiler.py", line 46, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['x86_64-apple-darwin13.4.0-clang', '-Wall', '-fPIC', '-I/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include', '-g', '-O3', '-m64', '-o', '/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.so', '/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c', '-shared', '-m64']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "example_peninsula.py", line 214, in <module>
    output=not args.nooutput, method=method[args.method])
  File "example_peninsula.py", line 130, in pensinsula_example
    pset.execute(k_adv + k_p, runtime=time, dt=dt, output_file=out)
  File "/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/particleset.py", line 253, in execute
    self.kernel.compile(compiler=GNUCompiler())
  File "/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/kernel.py", line 158, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/compiler.py", line 59, in compile
    raise RuntimeError(err)
RuntimeError: Error during compilation:
Compilation command: x86_64-apple-darwin13.4.0-clang -Wall -fPIC -I/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include -g -O3 -m64 -o /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.so /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c -shared -m64
Source file: /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c
Log file: /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.log
Log output: /var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:30:95: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(particle->lon, particle->lat, particle->depth, time, U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp0, &tmp1, LINEAR);
                                                                                              ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:78: note: passing argument to parameter 'xi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                             ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:30:110: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(particle->lon, particle->lat, particle->depth, time, U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp0, &tmp1, LINEAR);
                                                                                                             ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:88: note: passing argument to parameter 'yi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                       ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:30:125: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(particle->lon, particle->lat, particle->depth, time, U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp0, &tmp1, LINEAR);
                                                                                                                            ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:98: note: passing argument to parameter 'zi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                 ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:30:140: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(particle->lon, particle->lat, particle->depth, time, U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp0, &tmp1, LINEAR);
                                                                                                                                           ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:108: note: passing argument to parameter 'ti' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                           ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:42:92: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon1, lat1, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp2, &tmp3, LINEAR);
                                                                                           ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:78: note: passing argument to parameter 'xi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                             ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:42:107: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon1, lat1, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp2, &tmp3, LINEAR);
                                                                                                          ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:88: note: passing argument to parameter 'yi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                       ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:42:122: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon1, lat1, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp2, &tmp3, LINEAR);
                                                                                                                         ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:98: note: passing argument to parameter 'zi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                 ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:42:137: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon1, lat1, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp2, &tmp3, LINEAR);
                                                                                                                                        ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:108: note: passing argument to parameter 'ti' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                           ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:54:92: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon2, lat2, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp4, &tmp5, LINEAR);
                                                                                           ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:78: note: passing argument to parameter 'xi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                             ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:54:107: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon2, lat2, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp4, &tmp5, LINEAR);
                                                                                                          ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:88: note: passing argument to parameter 'yi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                       ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:54:122: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon2, lat2, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp4, &tmp5, LINEAR);
                                                                                                                         ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:98: note: passing argument to parameter 'zi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                 ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:54:137: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon2, lat2, particle->depth, (time + (0.5 * dt)), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp4, &tmp5, LINEAR);
                                                                                                                                        ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:108: note: passing argument to parameter 'ti' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                           ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:66:84: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon3, lat3, particle->depth, (time + dt), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp6, &tmp7, LINEAR);
                                                                                   ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:78: note: passing argument to parameter 'xi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                             ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:66:99: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon3, lat3, particle->depth, (time + dt), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp6, &tmp7, LINEAR);
                                                                                                  ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:88: note: passing argument to parameter 'yi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                       ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:66:114: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon3, lat3, particle->depth, (time + dt), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp6, &tmp7, LINEAR);
                                                                                                                 ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:98: note: passing argument to parameter 'zi' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                 ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:66:129: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolationUV(lon3, lat3, particle->depth, (time + dt), U, V, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp6, &tmp7, LINEAR);
                                                                                                                                ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:542:108: note: passing argument to parameter 'ti' here
                                                 CField *U, CField *V, void *xi, void *yi, void *zi, void *ti,
                                                                                                           ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:78:90: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolation(particle->lon, particle->lat, particle->depth, time, P, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp8, LINEAR);
                                                                                         ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:524:54: note: passing argument to parameter 'vxi' here
                                               void *vxi, void *vyi, void *vzi, void *vti, float *value, int interp_method)
                                                     ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:78:105: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolation(particle->lon, particle->lat, particle->depth, time, P, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp8, LINEAR);
                                                                                                        ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:524:65: note: passing argument to parameter 'vyi' here
                                               void *vxi, void *vyi, void *vzi, void *vti, float *value, int interp_method)
                                                                ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:78:120: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolation(particle->lon, particle->lat, particle->depth, time, P, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp8, LINEAR);
                                                                                                                       ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:524:76: note: passing argument to parameter 'vzi' here
                                               void *vxi, void *vyi, void *vzi, void *vti, float *value, int interp_method)
                                                                           ^
/var/folders/cy/qqfqlnkn6xn_fb6dnpw8cv2c0000gp/T/parcels-502/e8c5ee3c29f0b998690af39794053eb1.c:78:135: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
    err = temporal_interpolation(particle->lon, particle->lat, particle->depth, time, P, particle->cxi, particle->cyi, particle->czi, particle->cti, &tmp8, LINEAR);
                                                                                                                                      ^~~~~~~~~~~~~
/Users/davidlindo-atichati/miniconda2/envs/py2_parcels/lib/python3.6/site-packages/parcels/include/parcels.h:524:87: note: passing argument to parameter 'vti' here
                                               void *vxi, void *vyi, void *vzi, void *vti, float *value, int interp_method)
                                                                                      ^
20 warnings generated.
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
  "___stack_chk_fail", referenced from:
      _search_indices_vertical_s in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
  "___stack_chk_guard", referenced from:
      _search_indices_vertical_s in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
  "_cos", referenced from:
      _particle_loop in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
  "_floor", referenced from:
      _search_time_index in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
  "_printf", referenced from:
      _search_indices in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
  "_puts", referenced from:
      _temporal_interpolation in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
      _search_indices in e8c5ee3c29f0b998690af39794053eb1-4ff705.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by erikvansebille** [comment]
By the way, for future reference to other users, it would be good to add that the solution to go from the first error to the second one was to run `xcode-select --install`. This has resolved issues with xcode like this in the past

**Comment by willirath** [comment]
I also note that in the trace back, there seems to be a mixture of python 2 and 3. Can you try and start over with a completely new install following the note updated installation instructions that make sure that all is consistently in python 2?

http://oceanparcels.org/#installing

**Comment by erikvansebille** [comment]
Some thorough investigation by @willirath last week revealed that this is an issue with Anaconda and the latest version of macOS Xcode (9.3). While we await a fix from their side, a workaround for now is to run
```
export CC=gcc
```
in the terminal before running Parcels. No need then to change anything in the code itself.
