### ISSUE TITLE
downloading parcels

### ISSUE THREAD

**Issue by AshleighWomack** [OceanParcels/parcels#423]
Hi there. When I install Parcels it downloads alright but when I try open Spyder py2_parcels with Spyder from the anaconda launch it get an error and it won't launch Spyder. But the previous time I downloaded parcels everything worked. Am I doing something wrong? 

Traceback (most recent call last):
File "/Users/ashleighwomack/anaconda2/envs/py2_parcels/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: dlopen(/Users/ashleighwomack/anaconda2/envs/py2_parcels/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so, 2): Library not loaded: @rpath/libQt5WebEngineWidgets.5.dylib
Referenced from: /Users/ashleighwomack/anaconda2/envs/py2_parcels/lib/python3.6/site-packages/PyQt5/QtWebEngineWidgets.so
Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/ashleighwomack/anaconda2/envs/py2_parcels/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/ashleighwomack/anaconda2/envs/py2_parcels/lib/python3.6/site-packages/spyder/app/start.py", line 179, in main
from spyder.app import mainwindow
File "/Users/ashleighwomack/anaconda2/envs/py2_parcels/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/Users/ashleighwomack/anaconda2/envs/py2_parcels/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by erikvansebille** [comment]
This sounds more like a Spyder issue than a Parcels issue. I don't use Spyder myself, so not sure; but a quick google search returned pages such as https://github.com/spyder-ide/spyder/issues/4426

Could you check whether you can fix this by updating Spyder etc?
