### ISSUE TITLE
Temporary files 

### ISSUE THREAD

**Issue by slawchune** [OceanParcels/parcels#487]
Hi Philippe and Eric !  

I run multi independent launches of Parcels on a cluster (one submission is realized over 4 nodes of 32 processors = 128 Parcels processes at one time), and I am experiencing a saturation of the /tmp directory (limited to 4go on each node) for some of them. 

The issue is linked to size of the  "/tmp/parcels-911" directory.  I need some time to investigate on that, but :

1/ Is there a way to specify where those temporary files should be written, or is this hard coded ? 

2/ Could you confirm that those temporary files are deleted after each run ? In this case a saturation should not be reached for my application I suppose (each process is quite light).

```
root@node-01 tmp]# ll | more
total 76060
-rw------- 1 slawchune mercator  381152 Nov  6 02:34 cc01b3e1.o
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc01Fq7L.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc01Q9bb.s
-rw------- 1 slawchune mercator  639518 Nov  6 01:02 cc09gmLV.s
-rw------- 1 slawchune mercator       0 Nov  6 03:11 cc0Chajq.s
-rw------- 1 slawchune mercator       0 Nov  6 03:09 cc0ef5dB.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0f6PaY.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0HGPRH.s
-rw------- 1 slawchune mercator   20480 Nov  6 03:08 cc0JaKzr.out
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0Jl1fc.s
-rw------- 1 slawchune mercator       0 Nov  6 03:09 cc0Ki25K.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0LH1Vk.out
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0oC2sp.out
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0QC9jN.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0Rc7va.s
-rw------- 1 slawchune mercator  118784 Nov  6 03:08 cc0sBOBs.s
-rw------- 1 slawchune mercator       0 Nov  6 03:09 cc0tStHy.s
-rw------- 1 slawchune mercator       0 Nov  6 03:54 cc0WiFqS.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc0xZ3r8.err
-rw------- 1 slawchune mercator       0 Nov  6 03:32 cc10ibgr.s
-rw------- 1 slawchune mercator  586239 Nov  6 03:08 cc14BeEZ.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc1587A2.err
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc15BmLs.out
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc15IS7V.err
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cc16Gln8.out
.... 

-rw------- 1 slawchune mercator       0 Nov  6 03:53 ccZzMlFk.s
-rw------- 1 slawchune mercator       0 Nov  6 03:32 cczZPC1d.s
-rw------- 1 slawchune mercator       0 Nov  6 03:08 cczZpQVn.err
drwx------ 2 root      root       16384 Mar 21  2018 lost+found
drwx------ 6 jchanut   mercator    4096 Nov  5 19:12 ompi.node-01.579
drwxr-xr-x 2 slawchune mercator 4001792 Nov  6 03:08 parcels-911
drwx------ 3 root      root        4096 Jun 22 16:00 systemd-private-1efd34c08b6a482ba7ef445b7f06af15-ntpd.s
ervice-e4bS7q

```
Here is the error I get in the log file  : 

```
_"""
Traceback (most recent call last):
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/compiler.py", line 46, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wall', '-fPIC', '-I/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/include', '-g', '-O3', '-m64', '-o', '/var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.so', '/var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.c', '-shared', '-m64']' returned non-zero exit status -6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/data/rd_exchange2/slawchune/SMOC_CMEMS/Validation/Parcels/Validation/launch_parcels.py", line 110, in launch_parcels
    recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle} # handle out of domain particle
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/particleset.py", line 279, in execute
    self.kernel.compile(compiler=GNUCompiler())
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/kernel.py", line 159, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/compiler.py", line 59, in compile
    raise RuntimeError(err)
RuntimeError: Error during compilation:
Compilation command: gcc -Wall -fPIC -I/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/include -g -O3 -m64 -o /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.so /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.c -shared -m64
Source file: /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.c
Log file: /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.log

Log output: Cannot create temporary file in /tmp/: No space left on device

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multi_subprocesses_parcels.py", line 64, in <module>
    multi_subprocess_parcels(load_arg_sheet_file)
  File "multi_subprocesses_parcels.py", line 45, in multi_subprocess_parcels
    results = pool.starmap( launch_parcels.launch_parcels, args_array)
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Error during compilation:
Compilation command: gcc -Wall -fPIC -I/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/include -g -O3 -m64 -o /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.so /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.c -shared -m64
Source file: /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.c
Log file: /var/tmp/parcels-911/3ee783d36e155b01651a4eb86e5b3743.log

Log output: Cannot create temporary file in /tmp/: No space left on device_


```

Thank you for your lights !

**Comment by willirath** [comment]
That all this is written to a subdir of `/tmp/` is decided here:

https://github.com/OceanParcels/parcels/blob/6ccb27c2baae52610a02f9d8dc560367c40766b2/parcels/compiler.py#L3

https://github.com/OceanParcels/parcels/blob/6ccb27c2baae52610a02f9d8dc560367c40766b2/parcels/compiler.py#L22

and then passed on to

https://github.com/OceanParcels/parcels/blob/1a4251ce3ba496c3304958fdd4405fd3661ad695/parcels/kernel.py#L2

and

https://github.com/OceanParcels/parcels/blob/1a4251ce3ba496c3304958fdd4405fd3661ad695/parcels/rng.py#L1

Luckily, the underlying `tempfile.gettempdir()` checks a bunch of env vars to decide where to go: https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir

You should be able to choose whatever place you want by setting, e.g., `TMPDIR` to a bigger device:

```python
from os import environ
os.environ["TMPFILE"] = "/path/to/bigger/place/"
```

**Comment by slawchune** [comment]
Oh that's great ! thank you !

**Comment by slawchune** [comment]
Thanks !

I have changed the "tempfile.tempdir" to '/kara/data1/slawchune/tmp/', a disk space where all nodes can I/O. My temporary files are now well written where I want, but I still get an error : 

` INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/73771dde0688b7dc73d842042ae32be8.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/fd9da2746e4fab6367706d60a83a7cc3.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/fd9da2746e4fab6367706d60a83a7cc3.so
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/data/rd_exchange2/slawchune/SMOC_CMEMS/Validation/Parcels/Validation/launch_parcels.py", line 116, in launch_parcels
    recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle} # handle out of domain particle
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/particleset.py", line 280, in execute
    self.kernel.load_lib()
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/kernel.py", line 163, in load_lib
    self._lib = npct.load_library(self.lib_file, '.')
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/ctypes/__init__.py", line 426, in __getitem__
    return getattr(self, name)
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/ctypes/__init__.py", line 421, in __getattr__
    dll = self._dlltype(name)
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /kara/data1/slawchune/tmp/parcels-911/fd9da2746e4fab6367706d60a83a7cc3.so: invalid ELF header
"""`
I have googled "invalid ELF header" and it seemed related to issues with share libraries. 

Previously, when I wrote the temporary files directly on the /tmp/ of the concerned node, I also felt on some "file too short" for those temporary files on opening. Those errors are not produced on the master node, only for the slave ones. Was this ever experienced by other users ?

**Comment by slawchune** [comment]
Here is the error, but it only happens sometimes, not always. I feel like it's related to our cluster's file system configuration I will let you know if I have some news. Thanks !  

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multi_subprocesses_parcels.py", line 64, in <module>
    multi_subprocess_parcels(load_arg_sheet_file)
  File "multi_subprocesses_parcels.py", line 45, in multi_subprocess_parcels
    results = pool.starmap( launch_parcels.launch_parcels, args_array)
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/slawchune/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
OSError: /kara/data1/slawchune/tmp/parcels-911/a4210cb927480a3e666f6b113700d2bf.so: file too short
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/d69c534f89c3bf2e2039f8b73d4916f1.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/47a14d0592be2b42570a52e54c796f02.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/3f53bd58cebc067709f92aacbdc09e96.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/79e5c350b41740a59bac7742a6808c37.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/b9fa2948ebf9e23e45660ce912cddc7e.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/a22d5dbaeb2d72cd2a064b35c74aca55.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/38cbf100d402ce58b43dd68e6364e746.so
INFO: Compiled JITParticleAdvectionRK4periodicBC ==> /kara/data1/slawchune/tmp/parcels-911/e107fe52185e47e4f791b4364a5c89b6.so
```

**Comment by erikvansebille** [comment]
Hi @slawchune, is there any news on the temporary files? Is it, as you expected, related to your cluster's file system? Or something on the Parcels side?

**Comment by erikvansebille** [comment]
As we haven't heard anything for a while on the status of this issue, I'm assuming it's fixed and am now closing this issue

**Comment by slawchune** [comment]
Hi Eric and Phillip, 

Really sorry, I was monopolized by urgent tasks and I had to leave aside this activity with Parcels for several months. 

I've been trying to figured out again what's not working this week.  I haven't really been able to put my finger on something new. The behaviour is the same on the Meteo-France's cluster (beaufix) as on our own cluster in Mercator (kara).  

From what I understood in my previous tests, it is also related to a problem with compiling a C library on the fly when calling "particleset.py" by a pool.map. In the example bellow, the compiled library that is not working (File too short error) is  "/scratch/utmp/slurm/lawchunes.63079613/parcels-10736/e3778962831448f72c46ef78d9064e9f.so"

The thing is, I do this operation on a large number of processes. But I checked, there is no difference in memory size between the".so" files that don't work, and the ones that work. There doesn't seem to be any upstream problems either. 

It's always random, and the only solution I found was finally to resubmit the execution until it works. Fortunately, submissions work more often than they crash.


message : multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ext/mr/smer/lawchunes/SAVE/SMOC/Validation/SCRIPTS/launch_parcels.py", line 45, in launch_parcels_one_arg
    total_time_drift, file_out, id_buoy)
  File "/home/ext/mr/smer/lawchunes/SAVE/SMOC/Validation/SCRIPTS/launch_parcels.py", line 143, in launch_parcels
    recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle} # handle out of domain particle
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/particleset.py", line 280, in execute
    self.kernel.load_lib()
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/kernel.py", line 163, in load_lib
    self._lib = npct.load_library(self.lib_file, '.')
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/ctypes/__init__.py", line 426, in __getitem__
    return getattr(self, name)
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/ctypes/__init__.py", line 421, in __getattr__
    dll = self._dlltype(name)
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /scratch/utmp/slurm/lawchunes.63079613/parcels-10736/e3778962831448f72c46ef78d9064e9f.so: file too short
"""
---------------------------------------

**Comment by slawchune** [comment]
Here is the detail error regarding the C compilation. maybe I Misunderstood, but the.so files are compiled on the fly by a C library that the cluster can't share in subprocesses.D oes that mean more to you?

```
"""
Traceback (most recent call last):
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/compiler.py", line 49, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ext/mr/smer/lawchunes/SAVE/SMOC/Validation/SCRIPTS/launch_parcels.py", line 50, in launch_parcels_one_arg
    total_time_drift, file_out, id_buoy, add_windage, ln_drogue_off)
  File "/home/ext/mr/smer/lawchunes/SAVE/SMOC/Validation/SCRIPTS/launch_parcels.py", line 199, in launch_parcels
    recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle} # handle out of domain particle
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/particleset.py", line 319, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/kernel.py", line 178, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/home/ext/mr/smer/lawchunes/miniconda2/envs/env_py35/lib/python3.5/site-packages/parcels/compiler.py", line 53, in compile
    raise RuntimeError(err)
RuntimeError: OSError during compilation
Please check if compiler exists: gcc
"""
```
