### ISSUE TITLE
bug in multiple compilations

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#646]
I got this bug when parcels was compiled multiple times in a for loop:
```
Traceback (most recent call last):
  File "/home/staff/sebil001/parcels/parcels/compiler.py", line 53, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/home/staff/sebil001/miniconda3/envs/py3_parcels/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/staff/sebil001/miniconda3/envs/py3_parcels/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/staff/sebil001/miniconda3/envs/py3_parcels/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/staff/sebil001/miniconda3/envs/py3_parcels/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "microbes_eac_cmemsrun.py", line 89, in <module>
    pset.execute(SampleFields, dt=0, runtime=0)  # initial sampling
  File "/home/staff/sebil001/parcels/parcels/particleset.py", line 368, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))
  File "/home/staff/sebil001/parcels/parcels/kernel.py", line 194, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/home/staff/sebil001/parcels/parcels/compiler.py", line 57, in compile
    raise RuntimeError(err)
RuntimeError: OSError during compilation
```

This needs to be investigated

**Comment by erikvansebille** [comment]
This is fixed in #656
