### ISSUE TITLE
problem with globcurrent dataset  substract cannot use operands with dtype(M8[us]) and dtype ('o'))

### ISSUE THREAD

**Issue by mehrezboulares** [OceanParcels/parcels#658]
Hi,
there is a problem with globcurrent dataset i cant use parcel on this dataset perhaps this is related to juliandate and datetime ????
can you please help me?

**Comment by mehrezboulares** [comment]
<img width="715" alt="Capture" src="https://user-images.githubusercontent.com/10279232/65831110-8e441180-e2be-11e9-907b-66de5d02ded2.PNG">

**Comment by delandmeterp** [comment]
Hi,
This issue is very likely related to your data times which are not correctly parsed by the code. But it's hard to guess what's going wrong only with your log message.
Could you provide some minimal example reproducing the bug? (including the data files)

Thanks!

**Comment by mehrezboulares** [comment]
<img width="571" alt="Capture2" src="https://user-images.githubusercontent.com/10279232/66035591-14a56100-e514-11e9-8046-2b6dada27ed6.PNG">

dataset  globcurrent\nrt\global_025_deg\ekman_15m\2017\064

<img width="682" alt="Capture3" src="https://user-images.githubusercontent.com/10279232/66035636-2b4bb800-e514-11e9-9f89-d4e3c162004a.PNG">

the error
<img width="661" alt="Capture4" src="https://user-images.githubusercontent.com/10279232/66035800-7bc31580-e514-11e9-91fe-376d8b42efd6.PNG">

many thanks

**Comment by mehrezboulares** [comment]
i changed the datetime but also still the same error

<img width="594" alt="Capture2" src="https://user-images.githubusercontent.com/10279232/66035898-b331c200-e514-11e9-88fe-6bd8ebe93978.PNG">

**Comment by delandmeterp** [comment]
Could you upload the python file and the data files on a server (wetransfer, dropbox, ...) and provide me the link such that I can easily run your code? Thanks!

**Comment by mehrezboulares** [comment]
ok this a share link 

https://drive.google.com/drive/folders/1hwe6Os2GE0SLIdjaLnE5efluZ1rkdrU-?usp=sharing

**Comment by delandmeterp** [comment]
Indeed, there is an issue with the JulianDate. We'll have a look over it asap.

In the meantime, here is a version of your code that will pass:
```
from parcels import FieldSet, ParticleSet, JITParticle, AdvectionRK4
from datetime import timedelta, datetime
import numpy as np

filenames = {'U': "data/20*.nc",
             'V': "data/20*.nc"}
variables = {'U': 'u',
             'V': 'v'}
dimensions = {'lat': 'lat',
              'lon': 'lon',
              'time': 'time'}
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, deferred_load=False, allow_time_extrapolation=True)
fieldset.time_origin.time_origin = np.asarray(fieldset.time_origin.time_origin, 'datetime64[ns]')
fieldset.time_origin.calendar = 'np_datetime64'

pset = ParticleSet.from_line(fieldset=fieldset, size=5, pclass=JITParticle,
                             start=(31, -31), finish=(32, -31), time=np.datetime64('2017-05-03'))

pset.execute(AdvectionRK4, runtime=timedelta(days=7), dt=timedelta(minutes=5))
```

A few comments:
* I've rewritten the `fieldset.time_origin.time_origin` and `fieldset.time_origin.calendar` to convert them to the format I like (`np.datetime64`)
* I've also changed the format of the time in the pset creation, but it's not strictly necessary
* I have to put `deferred_load=False`. This is a strong restriction. Basically, if you let it at default=True, after some time, the simulation will load new time steps and there will be again problems with the conversion.
* (I also changed variable names which were wrong, and `allow_time_extrapolation` to True to have a full run)

So here comes a quick fix, but we'll do a proper fix as soon as possible.

**Comment by mehrezboulares** [comment]
many thanks for this fix i will try it i have another question please how can i access to the new x y coordinates of a particle after applying the ocean currents simulation (pset.execute) ? 
thnk you

**Comment by delandmeterp** [comment]
So, as I said it's a quick fix. We'll find an acceptable solution soon.

You can export your particleset to a netcdf file (see [this example](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_delaystart.ipynb))
But I guess your question was more how to access it directly within the code:
```
x = [p.lon for p in pset]
y = [p.lat for p in pset]
```

**Comment by mehrezboulares** [comment]
how i can make the map zoom in/out by using the code ?
thank you

**Comment by erikvansebille** [comment]
Dear @mehrezboulares. Thank you for reporting this bug. However, the types of questions that you're now asking are all covered in the tutorials at http://oceanparcels.org/#tutorials.

**Comment by ignasivalles** [comment]
Hi! I had similar issue than @mehrezboulares but following suggestions from @delandmeterp I got this error when I set `deferred_load=False`. In my case the model input is NEMO type ORCA025. Here my piece of code and the error which come up with `fieldset.from_nemo` function:

It may be some changes of numpy version? Because it didn't happen with old release...

```
mesh_mask = '/mnt/lustre/users/valles/DATA/NEMOINT_ORCA025/coordinates.nc'

variables = {'U': 'vozocrtx',
             'V': 'vomecrty',
             'W': 'vovecrtz',
             'T': 'votemper',
             'S': 'vosaline'}

dimensions= {'U': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'},
             'V': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'},
             'W': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'},
             'T': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'},
             'S': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'}}


Ufiles  = glob('/mnt/lustre/users/valles/DATA/NEMOINT_ORCA025/UCURR_ATLTROP025-INTER19582012_1960_2011_gridU.nc')
Vfiles  = glob('/mnt/lustre/users/valles/DATA/NEMOINT_ORCA025/VCURR_ATLTROP025-INTER19582012_1960_2011_gridV.nc')

Wfiles  = glob('/mnt/lustre/users/valles/DATA/NEMOINT_ORCA025/ATLTROP025-INTER19582012_1960_2011_gridW.nc')
Tfiles  = glob('/mnt/lustre/users/valles/DATA/NEMOINT_ORCA025/Temp_ATLTROP025-INTER19582012_1960_2011_gridT.nc')
Sfiles  = glob('/mnt/lustre/users/valles/DATA/NEMOINT_ORCA025/Sal_ATLTROP025-INTER19582012_1960_2011_gridT.nc')

filenames = {'U': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Ufiles},
             'V': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Vfiles},
             'W': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Wfiles},
             'T': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Tfiles},
             'S': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Sfiles}}

fieldset = FieldSet.from_nemo(filenames, variables, dimensions, deferred_load=False, tracer_interp_method='cgrid_tracer', allow_time_extrapolation=True)
fieldset.time_origin.time_origin = np.asarray(fieldset.time_origin.time_origin, 'datetime64[ns]')
fieldset.time_origin.calendar = 'np_datetime64'


Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 377, in apply_along_axis
    ind0 = next(inds)
StopIteration
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parcels-TAB-ORCA-2.py", line 57, in <module>
    fieldset = FieldSet.from_nemo(filenames, variables, dimensions, deferred_load=False, tracer_interp_method='cgrid_tracer', allow_time_extrapolation=True)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/parcels/fieldset.py", line 363, in from_nemo
    allow_time_extrapolation=allow_time_extrapolation, tracer_interp_method=tracer_interp_method, **kwargs)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/parcels/fieldset.py", line 437, in from_c_grid_dataset
    allow_time_extrapolation=allow_time_extrapolation, interp_method=interp_method, **kwargs)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/parcels/fieldset.py", line 301, in from_netcdf
    fieldtype=fieldtype, **kwargs)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/parcels/field.py", line 374, in from_netcdf
    data = lib.concatenate(data_list, axis=0)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/dask/array/core.py", line 3420, in concatenate
    meta = np.concatenate([meta_from_array(s) for s in seq], axis=axis)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/common.py", line 132, in __array__
    return np.asarray(self.values, dtype=dtype)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/dataarray.py", line 568, in values
    return self.variable.values
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/variable.py", line 437, in values
    return _as_array_or_item(self._data)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/variable.py", line 250, in _as_array_or_item
    data = np.asarray(data)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/indexing.py", line 676, in __array__
    self._ensure_cached()
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/indexing.py", line 673, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/indexing.py", line 652, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/indexing.py", line 556, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/coding/variables.py", line 73, in __array__
    return self.func(self.array)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/coding/variables.py", line 142, in _apply_mask
    data = np.asarray(data, dtype=dtype)
File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/coding/variables.py", line 73, in __array__
    return self.func(self.array)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/coding/variables.py", line 142, in _apply_mask
    data = np.asarray(data, dtype=dtype)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/indexing.py", line 556, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 72, in __getitem__
    key, self.shape, indexing.IndexingSupport.OUTER, self._getitem
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/core/indexing.py", line 836, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 84, in _getitem
    array = getitem(original_array, key)
  File "netCDF4/_netCDF4.pyx", line 4095, in netCDF4._netCDF4.Variable.__getitem__
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/netCDF4/utils.py", line 402, in _StartCountStride
    start[...,i] = np.apply_along_axis(lambda x: e*x, i, np.ones(sdim[:-1]))
  File "/opt/ohpc/pub/apps/anaconda37/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    raise ValueError('Cannot apply_along_axis when any iteration dimensions are 0')
ValueError: Cannot apply_along_axis when any iteration dimensions are 0
                                                                                                                                                                                              
```
