### ISSUE TITLE
Issue getting Parcel Tutorial animations to run

### ISSUE THREAD

**Issue by dan97wilson** [OceanParcels/parcels#677]
I am new to Parcels so working my way through the tutorials, on the 1st tutorial I can't seem to get the animations using the `mode= 'movie2d_notebook'` to run. I am using Spyder to run this code after downloading Anaconda and then parcels. Apologies if it is something simple that I have missed/done wrong!

I have used all the code from the tutorial apart from 
`%matplotlib inline` (which comes up as invalid syntax, so I have tried removing this line of code and setting graphics preference via tools-preferences toolbar to automatic and inline, both of which allow non animated visualisations to work but not the animated visualisations).

The issue is when I run the code
```
output_file.export()
plotTrajectoriesFile('EddyParticles.nc'); 
```
I get the following error code

`AttributeError: 'ParticleFile' object has no attribute 'export'`

I have tried removing the `output_file.export()` line of code and this lets the code
`plotTrajectoriesFile('EddyParticles.nc'); ` plot a visualisation 

But the code 
`plotTrajectoriesFile('EddyParticles.nc', mode='movie2d_notebook')`

doesn't produce the animation and produces the following error
```
Out[23]: <matplotlib.animation.FuncAnimation at 0x277792f4278>Traceback (most recent call last):
  File "C:\Users\dw421\AppData\Local\Continuum\anaconda3\envs\py3_parcels\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "C:\Users\dw421\AppData\Local\Continuum\anaconda3\envs\py3_parcels\lib\site-packages\matplotlib\animation.py", line 957, in _start
    self.event_source.add_callback(self._step)
AttributeError: 'NoneType' object has no attribute 'add_callback'
```

**Comment by erikvansebille** [comment]
Thanks for reporting @dan97wilson! I tried creating a animation like you, and also got an error. However, it was a different error from yours:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/matplotlib/animation.py in _repr_html_(self)
   1421         fmt = rcParams['animation.html']
   1422         if fmt == 'html5':
-> 1423             return self.to_html5_video()
   1424         elif fmt == 'jshtml':
   1425             return self.to_jshtml()

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/matplotlib/animation.py in to_html5_video(self, embed_limit)
   1351                                 bitrate=rcParams['animation.bitrate'],
   1352                                 fps=1000. / self._interval)
-> 1353                 self.save(f.name, writer=writer)
   1354 
   1355             # Now open and base64 encode

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1198                         # TODO: See if turning off blit is really necessary
   1199                         anim._draw_next_frame(d, blit=False)
-> 1200                     writer.grab_frame(**savefig_kwargs)
   1201 
   1202         # Reconnect signal for first draw if necessary

~/anaconda3/envs/py3_parcels/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
    239             yield self
    240         finally:
--> 241             self.finish()
    242 
    243 

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/matplotlib/animation.py in finish(self)
    365     def finish(self):
    366         '''Finish any processing for writing the movie.'''
--> 367         self.cleanup()
    368 
    369     def grab_frame(self, **savefig_kwargs):

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/matplotlib/animation.py in cleanup(self)
    403     def cleanup(self):
    404         '''Clean-up and collect the process used to write the movie file.'''
--> 405         out, err = self._proc.communicate()
    406         self._frame_sink().close()
    407         _log.debug('MovieWriter -- Command stdout:\n%s', out)

~/anaconda3/envs/py3_parcels/lib/python3.6/subprocess.py in communicate(self, input, timeout)
    861 
    862             try:
--> 863                 stdout, stderr = self._communicate(input, endtime, timeout)
    864             finally:
    865                 self._communication_started = True

~/anaconda3/envs/py3_parcels/lib/python3.6/subprocess.py in _communicate(self, input, endtime, orig_timeout)
   1523                     selector.register(self.stdin, selectors.EVENT_WRITE)
   1524                 if self.stdout:
-> 1525                     selector.register(self.stdout, selectors.EVENT_READ)
   1526                 if self.stderr:
   1527                     selector.register(self.stderr, selectors.EVENT_READ)

~/anaconda3/envs/py3_parcels/lib/python3.6/selectors.py in register(self, fileobj, events, data)
    349 
    350         def register(self, fileobj, events, data=None):
--> 351             key = super().register(fileobj, events, data)
    352             poll_events = 0
    353             if events & EVENT_READ:

~/anaconda3/envs/py3_parcels/lib/python3.6/selectors.py in register(self, fileobj, events, data)
    235             raise ValueError("Invalid events: {!r}".format(events))
    236 
--> 237         key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
    238 
    239         if key.fd in self._fd_to_key:

~/anaconda3/envs/py3_parcels/lib/python3.6/selectors.py in _fileobj_lookup(self, fileobj)
    222         """
    223         try:
--> 224             return _fileobj_to_fd(fileobj)
    225         except ValueError:
    226             # Do an exhaustive search.

~/anaconda3/envs/py3_parcels/lib/python3.6/selectors.py in _fileobj_to_fd(fileobj)
     37         except (AttributeError, TypeError, ValueError):
     38             raise ValueError("Invalid file object: "
---> 39                              "{!r}".format(fileobj)) from None
     40     if fd < 0:
     41         raise ValueError("Invalid file descriptor: {}".format(fd))

ValueError: Invalid file object: <_io.BufferedReader name=63>
```

This seems a bug in `matplotlib`, that is not really something we can fix from our end. Hopefully this will be fixed soon by the `matplotlib` team and their next version?

By the way, the error with `%matplotlib inline` can be fixed by replacing with `%pylab inline`

**Comment by dan97wilson** [comment]
Hi Erik, thanks for getting back to me so quickly. No worries, that's understandable, the tutorials will still be really helpful to get a hang of the basic Parcels code so will keep working through them and will check back to see if the matplotlib bug gets fixed next time the matplotlib team release a new version.

Thanks for the tip about `%pylab inline` that will come in handy!

**Comment by erikvansebille** [comment]
The animations work well on the binder (https://mybinder.org/v2/gh/OceanParcels/parcels_examples_binder/master?urlpath=lab/tree/parcels_examples/parcels_tutorial.ipynb) so closing this Issue now
