### ISSUE TITLE
gcc compiler

### ISSUE THREAD

**Issue by ignasivalles** [OceanParcels/parcels#695]
When I'm sending job into a cluster I have a problem regarding to cc compilation, It seems it doesn't call the gcc installed from the system correctly, which is the gcc 8.3.0 version. 

Maybe this issue it's not in your hands, but I'm losing lot of time trying to solve it. Any help would be appreciated.

The issue looks like that:

```
Traceback (most recent call last):
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/compiler.py", line 55, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wall', '-fPIC', '-I/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/include', '-g', '-O3', '-DDOUBLE_COORD_VARIABLES', '-m64', '-o', '/tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.so', '/tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.c', '-shared', '-m64']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_MOCBOX_forward2v1.py", line 179, in <module>
    pset.execute(kernels, runtime=delta(days=timest_out), dt=delta(hours=timest_calc), recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle}, verbose_progress=False) 
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particleset.py", line 382, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/kernel.py", line 211, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/compiler.py", line 68, in compile
    raise RuntimeError(err)
RuntimeError: Error during compilation:
Compilation command: gcc -Wall -fPIC -I/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/include -g -O3 -DDOUBLE_COORD_VARIABLES -m64 -o /tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.so /tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.c -shared -m64
Source file: /tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.c
Log file: /tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.log

Log output: In file included from /tmp/parcels-10119/fb2057c1e5691a427c34a53b44dfb61a_0.c:1:
/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/include/parcels.h:7:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.

Exception ignored in: <function ParticleFile.__del__ at 0x2b8041bdbe18>
Traceback (most recent call last):
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 195, in __del__
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 200, in close
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 361, in export
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
NameError: name 'open' is not defined
```

**Comment by ignasivalles** [comment]
problem solved, the gcc version of the main system was different from the cluster
