### ISSUE TITLE
Strided arrays

### ISSUE THREAD

**Issue by ursho2552** [OceanParcels/parcels#789]
Hello,

I am currently running a simulation and it appears to work with a previous version. After updating the parcels package I received the following error:

```
Traceback (most recent call last):
  File "Debug_main.py", line 110, in <module>
    pset.execute(kernels, runtime=delta(days=5), dt=delta(hours=1))
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 652, in execute
    execute_once=execute_once)
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/kernel.py", line 377, in execute
    self.execute_jit(pset, endtime, dt)
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/kernel.py", line 253, in execute_jit
    particle_data = byref(pset.ctypes_struct)
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 315, in ctypes_struct
    cdata = [cdata_for(v) for v in self.ptype.variables]
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 315, in <listcomp>
    cdata = [cdata_for(v) for v in self.ptype.variables]
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 302, in cdata_for
    cdata_array = np.ctypeslib.as_ctypes(self.particle_data[v.name])
  File "/home/ursho/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/numpy/ctypeslib.py", line 531, in as_ctypes
    raise TypeError("strided arrays not supported")
TypeError: strided arrays not supported

```
My setup is as follows, where "mask_u" is the ocean-land mask in our ROMS setup:

```

data_file = "uvw_pactcs30_10_days.nc"
depthfiles = "depth_z_pos.nc"
mesh_file = "pactcs30_grd.nc"    
          
filenames = {'U': {'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': data_file},
                 'V': {'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': data_file},
                 'W': {'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': data_file},
                 'maskU': {'lon': mesh_file, 'lat': mesh_file, 'data': mesh_file}}
               
variables = {'U': 'u',
                 'V': 'v',
                 'W': 'w',
                 'maskU': 'mask_u'}
             
dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z', 'time': 'time_counter'},
                  'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z', 'time': 'time_counter'},
                  'W': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z', 'time': 'time_counter'},
                  'maskU': {'lon': 'lon_psi', 'lat': 'lat_psi'}}

    
fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions,allow_time_extrapolation=False)
```
The setup appears to work, if only U, V, and W are defined in the fieldset, or if only one particle is simulated. As soon as the particle set has more than one particle, the error appears. Below are the some tests to show this behaviour. The simulation works for both particles individually, but not if they are in the same particle set.

```
pset = ParticleSet(fieldset=fieldset, pclass=JITParticle, lon=233.418167,\
                   lat=47.519787,depth=0.488973,time=0.0)
kernels =  pset.Kernel(AdvectionRK4_3D)
pset.execute(kernels, runtime=delta(days=5), dt=delta(hours=1))
    
pset = ParticleSet(fieldset=fieldset, pclass=JITParticle, lon=235.439484,\
                   lat=42.997616,depth=3.693717,time=0.0)
pset.execute(kernels, runtime=delta(days=5), dt=delta(hours=1))
    
pset = ParticleSet(fieldset=fieldset, pclass=JITParticle, lon=[233.418167,235.439484],\
                   lat=[47.519787,42.997616],depth=[0.488973,3.693717],time=0.0)
pset.execute(kernels, runtime=delta(days=5), dt=delta(hours=1))
```
The three files needed are [here](https://we.tl/t-4tyojFixie)

Thank you for your help!

**Comment by angus-g** [comment]
Should be fixed by #785 shortly!

**Comment by erikvansebille** [comment]
#785 has been merged, so this should be fixed now. Could you rerun with the new `master`, @ursho2552? I'm closing this Issue, but if you still experience the error, please reopen this Issue.

**Comment by ursho2552** [comment]
Yes thank you very much, it works now.
