### ISSUE TITLE
Particle boolean index dimension error in Parcels 2.1.5

### ISSUE THREAD

**Issue by HaydenSchilling** [OceanParcels/parcels#820]
Hi, I'm trying to get some simple models to run on a HPC (before scaling up) and as part of this i updated my desktop parcels to 2.1.5 (to match the HPC) and now a script that was working on 2.1.4 no longer works and I'm stumped. If I reinstall 2.1.4 on both the HPC and my computer the script runs fine. I'm trying to run a nemo3D grid. 

The error message is:
```
runfile('C:/Users/hayde/Crab-Dispersal/Crab_Dispersal.py', wdir='C:/Users/hayde/Crab-Dispersal')
INFO: Compiled SampleParticleAdvectionRK4SampleTempSampleBathySampleDistanceSampleAgeBrownianMotion2D ==> C:\Users\hayde\AppData\Local\Temp\parcels-tmp\b3a6a77ee58f6c09fbd6a01f41db2fdc_0.dll
Traceback (most recent call last):

  File "C:\Users\hayde\Crab-Dispersal\Crab_Dispersal.py", line 184, in <module>
    endtime=end_time)

  File "C:\Users\hayde\.conda\envs\py3_parcels\lib\site-packages\parcels\particleset.py", line 643, in execute
    execute_once=execute_once)

  File "C:\Users\hayde\.conda\envs\py3_parcels\lib\site-packages\parcels\kernel.py", line 382, in execute
    remove_deleted(pset)

  File "C:\Users\hayde\.conda\envs\py3_parcels\lib\site-packages\parcels\kernel.py", line 362, in remove_deleted
    pset.remove_booleanvector(indices)

  File "C:\Users\hayde\.conda\envs\py3_parcels\lib\site-packages\parcels\particleset.py", line 501, in remove_booleanvector
    self.particle_data[d] = self.particle_data[d][~indices, ...]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 2
```
Let me know I can provide any more information.

**Comment by erikvansebille** [comment]
Hi @HaydenSchilling. This is indeed a bug in Parcels 2.1.5, as also reported in #789 and #804. It's fixed in the `master` branch now. 

If you don't want to wait for the next Parcels release, you could use the `master` branch following the installation instructions on oceanparcels.org. Otherwise, keep working with v2.1.4

**Comment by HaydenSchilling** [comment]
Thanks @erikvansebille , we'll keep running with 2.1.4 for now!
