### ISSUE TITLE
Correct cell not found as particle crosses nested model border

### ISSUE THREAD

**Issue by DEHewitt** [OceanParcels/parcels#889]
Hi,

I am attempting to nest a small scale oceanographic model, which is configured in the Regional Oceanographic Modelling System (NEMO grid; described here: https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2019JC015227) within BRAN 3p5, configured using the Ocean Forecasting Australia Model (which is a configuration of the GFDL Modular Ocean Model; details here: https://wp.csiro.au/bluelink/global/bran/). 

I am using version 2.1.4 of Parcels and attempting to run these simulations on the HPC at UNSW (Katana). I have successfully run small scale simulations (i.e. 1 particle released every 4 days from 4 locations) - that is the output looks how I expect it to - however, associated with the output is an error/warning log with the following message:

```
Correct cell not found for (154.050926, -25.534158) after 1000000 iterations
Debug info: old particle indices: (yi, xi) 314 45
            new particle indices: (yi, xi) 314 226
            Mesh 2d shape:  316 271
            Relative particle position:  (xsi, eta) -6.1320155892265049e-01 1.0127507928492394e+00
```

When I attempt to scale up to full scale simulations (i.e. 100 particles released daily from 10 locations) the jobs consistently time out with the same error/warning message. 

These coordinates roughly match the boundary where particles pass from one model into the next.

The following is the code used to run the simulations:

```
from parcels import FieldSet, Field, AdvectionRK4, ParticleSet, JITParticle, Variable, BrownianMotion2D, random, NestedField
from parcels import ErrorCode
import numpy as np
from glob import glob
from datetime import timedelta as delta
from datetime import datetime as datetime
import math
import os
from operator import attrgetter

out_dir = '/home/z5278054/Nesting'

npart = 1  # number of particles to be released
repeatdt = delta(days=4)  # release from the same set of locations every X day

# Forward: 9
# lon_array = []
# lat_array = []

# Backwards: 13
lon_array = [153.790]#, 153.799, 153.736, 153.172, 153.048, 152.946, 152.775, 152.312, 152.045, 151.577]
lat_array = [-28.165]#, -28.890, -29.432, -30.864, -31.645, -31.899, -32.193, -32.719, -32.917, -33.578]

lon = np.repeat(lon_array,npart)
lat = np.repeat(lat_array,npart)

array_ref = 0 # which season to simulate (0 = 1994/95, 22 = 2015/16)

# Spawning season is September to March (Heasman et al. 1985)
# Reality language: start date will be 30th August and run until 15th May (the year after) to allow for the full 40 days of tracking.
# Particle reality: the first day of life (and hence the 'start') for particles will be 15th May.

year_array = np.arange(1994, 2016, 1)

start_time = datetime(year_array[array_ref], 8, 30) # year, month, day
end_time = datetime(year_array[array_ref]+1, 5, 10)  #year, month, day

# Set diffusion constants (in m/s)
Kh_zonal = 10
Kh_meridional = 10

# Define BRAN fieldset
filenames_BRAN = {'U': sorted(glob('/srv/scratch/z3374139/BRAN_AUS/Ocean_u_*')),
                  'V': sorted(glob('/srv/scratch/z3374139/BRAN_AUS/Ocean_v_*')),
                  'temp': sorted(glob('/srv/scratch/z3374139/BRAN_AUS/Ocean_temp_*'))}

variables_BRAN = {'U': 'u',
             'V': 'v',
             'temp': 'temp'}

dimensions_BRAN = {}
dimensions_BRAN['U'] = {'lat': 'yu_ocean', 'lon': 'xu_ocean', 'depth': 'st_ocean', 'time': 'Time'}
dimensions_BRAN['V'] = {'lat': 'yu_ocean', 'lon': 'xu_ocean', 'depth': 'st_ocean', 'time': 'Time'}
dimensions_BRAN['temp'] = {'lat': 'yt_ocean', 'lon': 'xt_ocean', 'depth': 'st_ocean', 'time': 'Time'} 

indices_BRAN = {'depth': [0]} # surface? not sure how many layers BRAN has

fieldset_BRAN = FieldSet.from_netcdf(filenames_BRAN, variables_BRAN, dimensions_BRAN, allow_time_extrapolation = True)

fieldset_BRAN.add_constant('maxage', 40.*86400)
fieldset_BRAN.temp.interp_method = 'nearest'

# Define ROMS fieldset
ufiles = sorted(glob('/srv/scratch/z3097808/20year_run/20year_freerun_output_NEWnci/outer_avg_*'))
ufiles = ufiles
vfiles = ufiles
tfiles = ufiles
mesh_mask = '/home/z5278054/EACouter_mesh_srho.nc' 

filenames_ROMS = {'U': ufiles,
             'V': vfiles,
             'temp': tfiles,
             'mesh_mask': mesh_mask}

variables_ROMS = {'U': 'u',
             'V': 'v',
             'temp': 'temp'}

dimensions_ROMS = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 's_rho', 'time': 'ocean_time'},
             'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 's_rho', 'time': 'ocean_time'},
             'temp': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 's_rho', 'time': 'ocean_time'}}

indices_ROMS = {'depth': [29]} # surface?

fieldset_ROMS = FieldSet.from_nemo(filenames_ROMS, variables_ROMS, dimensions_ROMS, indices_ROMS, allow_time_extrapolation=True)
fieldset_ROMS.add_constant('maxage', 40.*86400)
fieldset_ROMS.temp.interp_method = 'nearest'

out_file = str(out_dir)+'/'+str(year_array[array_ref])+'_Back.nc' # be sure to change naming for back/forawrd runs

# If output file already exists then remove it
if os.path.exists(out_file):
    os.remove(out_file)
    
def DeleteParticle(particle, fieldset, time):
    particle.delete()

# Nest the two models    
U = NestedField('U', [fieldset_ROMS.U, fieldset_BRAN.U])
V = NestedField('V', [fieldset_ROMS.V, fieldset_BRAN.V])
temp = NestedField('temp', [fieldset_ROMS.temp, fieldset_BRAN.temp]) 
fieldset = FieldSet(U, V)

fieldset.add_field(temp)
fieldset.temp.interp_method = 'nearest'

# Keep track of which field is being interpolated: Box 6 & 7 https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_NestedFields.ipynb
# This was modified to match the code block below as it was having a similar error due to the grid not being defined right.
# Adding this made the code REALLY SLOW - Once we confirm the nesting is working correctly, I suggest removing (commenting out).
size2D_ROMS = (fieldset_ROMS.U.grid.ydim, fieldset_ROMS.U.grid.xdim)
size2D_BRAN = (fieldset_BRAN.U.grid.ydim, fieldset_BRAN.U.grid.xdim)
F1 = Field('F1', np.ones((size2D_ROMS), dtype=np.float32), lon=fieldset.U[0].grid.lon, lat=fieldset.U[0].grid.lat, mesh='spherical')
F2 = Field('F2', 2*np.ones((size2D_BRAN), dtype=np.float32), lon=fieldset.U[1].grid.lon, lat=fieldset.U[1].grid.lat, mesh='spherical')
F = NestedField('F', [F1, F2])
fieldset.add_field(F)

# Create field of Kh_zonal and Kh_meridional, using same grid as U
# See Eriks comment on github: https://github.com/OceanParcels/parcels/issues/798
# Note this now uses the BRAN grid (shown by the [1]) not the ROMS grid (which was [0])
size2D_1 = (fieldset.U[1].grid.ydim, fieldset.U[1].grid.xdim)
fieldset.add_field(Field('Kh_zonal', Kh_zonal*np.ones(size2D_1), 
                         lon=fieldset.U[1].grid.lon, lat=fieldset.U[1].grid.lat, mesh='spherical'))
fieldset.add_field(Field('Kh_meridional', Kh_meridional*np.ones(size2D_1), 
                         lon=fieldset.U[1].grid.lon, lat=fieldset.U[1].grid.lat, mesh='spherical'))

fieldset.add_constant('maxage', 40.*86400)

random.seed(123456) # Set random seed

class SampleParticle(JITParticle): # Define a new particle class
    age = Variable('age', dtype=np.float32, initial=0.) # initialise age
    temp = Variable('temp', dtype=np.float32, initial=fieldset.temp[0])  # initialise temperature
    distance = Variable('distance', initial=0., dtype=np.float32)  # the distance travelled
    prev_lon = Variable('prev_lon', dtype=np.float32, to_write=False,
                        initial=attrgetter('lon'))  # the previous longitude
    prev_lat = Variable('prev_lat', dtype=np.float32, to_write=False,
                        initial=attrgetter('lat'))  # the previous latitude.
    f = Variable('f', dtype=np.int32) # Identifies the grid the particle is in (ROMS or BRAN)

def SampleDistance(particle, fieldset, time):
    # Calculate the distance in latitudinal direction (using 1.11e2 kilometer per degree latitude)
    lat_dist = (particle.lat - particle.prev_lat) * 1.11e2
    # Calculate the distance in longitudinal direction, using cosine(latitude) - spherical earth
    lon_dist = (particle.lon - particle.prev_lon) * 1.11e2 * math.cos(particle.lat * math.pi / 180)
    # Calculate the total Euclidean distance travelled by the particle
    particle.distance += math.sqrt(math.pow(lon_dist, 2) + math.pow(lat_dist, 2))
    particle.prev_lon = particle.lon  # Set the stored values for next iteration.
    particle.prev_lat = particle.lat
    
def SampleAge(particle, fieldset, time):
    particle.age = particle.age + math.fabs(particle.dt)
    if particle.age > fieldset.maxage:
        particle.delete()

# Kernel to identify which grid a particle is in (Very slow once this is included)        
#def SampleNestedFieldIndex(particle, fieldset, time):
 #   particle.f = fieldset.F[time, particle.depth, particle.lat, particle.lon]

def SampleTemp(particle, fieldset, time):
    particle.temp = fieldset.temp[time, particle.depth, particle.lat, particle.lon]

end_time = np.repeat(end_time,len(lon))

pset = ParticleSet.from_list(fieldset, pclass=SampleParticle, lon=lon, lat=lat, time=end_time, repeatdt=repeatdt)

pfile = pset.ParticleFile(out_file, outputdt=delta(days=1))

kernels = pset.Kernel(AdvectionRK4) + SampleAge + SampleDistance + BrownianMotion2D #+ SampleNestedFieldIndex + SampleTemp #+ SampleBathy

pset.execute(kernels, 
             dt=-delta(minutes=5), # interpolation timestep, positive/negative for forwards/backwards
             output_file=pfile, 
             verbose_progress=True,
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
			 endtime = start_time)
pfile.close()
```

Any tips you can provide would be greatly appreciated!

**Comment by DEHewitt** [comment]
```test
more testin```

**Comment by DEHewitt** [comment]
```
test
second line
```

**Comment by erikvansebille** [comment]
Hi @DEHewitt, thanks for reporting this. I haven't worked much with nested fields yet, so haven't seen this problem myself.

As a workaround, you could try reducing the `itMax` value at https://github.com/OceanParcels/parcels/blob/master/parcels/include/index_search.h#L201. 100,000 is arguably a bit high number for this, and reducing it to e.g. 10 may speed up the code. Especially on rectangular (i.e. non-Curvilinear) Grids, the index search algorithm should only need a handful of iterations maximum. Can you give that a try?

**Comment by DEHewitt** [comment]
Hi @erikvansebille, thanks for the speedy response!

I have followed your advice and forked, edited and installed the latest version of parcels (v2.2.0). However, am running into a different issue now and getting the following warnings/errors:
```
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:335: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  timeslices = np.array(timeslices)
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:337: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dataFiles = np.concatenate(np.array(dataFiles))
WARNING: Casting lon data to np.float32
WARNING: Casting lat data to np.float32
WARNING: Casting depth data to np.float32
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:335: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  timeslices = np.array(timeslices)
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:337: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dataFiles = np.concatenate(np.array(dataFiles))
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:335: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  timeslices = np.array(timeslices)
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:337: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dataFiles = np.concatenate(np.array(dataFiles))
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:335: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  timeslices = np.array(timeslices)
/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py:337: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dataFiles = np.concatenate(np.array(dataFiles))
WARNING: Trying to initialize a shared grid with different chunking sizes - action prohibited. Replacing requested field_chunksize with grid's master chunksize.
WARNING: Casting field data to np.float32
INFO: Compiled random ==> /scratch/pbs.491672.kman.restech.unsw.edu.au/parcels-15278054/parcels_random_a1b191d8-b0e0-41d5-a6b1-928875572d40.so
Traceback (most recent call last):
  File "nest_BRAN_ROMS_0.py", line 166, in <module>
    pset = ParticleSet.from_list(fieldset, pclass=SampleParticle, lon=lon, lat=lat, time=end_time, repeatdt=repeatdt)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/particleset.py", line 342, in from_list
    return cls(fieldset=fieldset, pclass=pclass, lon=lon, lat=lat, depth=depth, time=time, repeatdt=repeatdt, lonlatdepth_dtype=lonlatdepth_dtype, **kwargs)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/particleset.py", line 278, in __init__
    v.initial.fieldset.computeTimeChunk(time[i], 0)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/fieldset.py", line 932, in computeTimeChunk
    data = f.computeTimeChunk(data, tind)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py", line 1306, in computeTimeChunk
    buffer_data = filebuffer.data
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py", line 2114, in data
    return self.data_access()
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py", line 2204, in data_access
    data = data.rechunk(self.chunk_mapping)
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 2201, in rechunk
    return rechunk(self, chunks, threshold, block_size_limit)
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/rechunk.py", line 233, in rechunk
    chunks = normalize_chunks(
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 2484, in normalize_chunks
    chunks = sum(
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 2486, in <genexpr>
    blockdims_from_blockshape((s,), (c,))
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 974, in blockdims_from_blockshape
    return tuple(
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 975, in <genexpr>
    ((bd,) * (d // bd) + ((d % bd,) if d % bd else ()) if d else (0,))
ZeroDivisionError: integer division or modulo by zero
```

The code used is the same (except `BrownianMotion2D` was changed to `DiffusionUniformKh`). I attempted to run another simulation (below) that doesn't use nested fields and got a similar error (bottom). All code was written (and worked) in version 2.1.4 - I note there have been some changes to `dask` in recent releases and that seems to be what is causing the issue here.

Non-nested code
```
from parcels import FieldSet, Field, AdvectionRK4, ParticleSet, JITParticle, Variable, DiffusionUniformKh, random
from parcels import ErrorCode
import numpy as np
from glob import glob
#import time as timelib
from datetime import timedelta as delta
from datetime import datetime as datetime
#import cartopy
import math
import os
from operator import attrgetter

out_dir = '/home/z5278054/Nesting'

npart = 1  # number of particles to be released
repeatdt = delta(days=1)  # release from the same set of locations every X day

# Forward: 9
# lon_array = []
# lat_array = []

# Backwards: 13
lon_array = [153.790]#, 153.799, 153.736, 153.172, 153.048, 152.946, 152.775, 152.312, 152.045, 151.577]
lat_array = [-28.165]#, -28.890, -29.432, -30.864, -31.645, -31.899, -32.193, -32.719, -32.917, -33.578]

lon = np.repeat(lon_array,npart)
lat = np.repeat(lat_array,npart)

array_ref = 0 # which season to simulate (0 = 1994/95, 22 = 2015/16)

# Spawning season is September to March (Heasman et al. 1985)
# Reality language: start date will be 30th August and run until 15th May (the year after) to allow for the full 40 days of tracking.
# Particle reality: the first day of life (and hence the 'start') for particles will be 15th May.

# Manually set the filenames. The names correspond to the number of days since 1, 1, 1990
file_nos = np.arange(1461, 9742, 30)
year_array = np.arange(1994, 2016, 1)

# Days since 1990
start_time = datetime(year_array[array_ref],8, 30) # year, month, day
start_dys = start_time-datetime(1990,1,1) + delta(days=1)
start_id = np.where(file_nos<=start_dys.days) #Find the reference file location
start_id = start_id[0][-1]

end_time = datetime(year_array[array_ref]+1, 5, 15)  #year, month, day
end_dys = end_time-datetime(1990,1,1) + delta(days=1)
end_id = np.where(file_nos>=end_dys.days) #Find the reference file location
end_id = end_id[0][0]

runtime = end_time-start_time + delta(days=1)

ufiles = sorted(glob('/srv/scratch/z3097808/20year_run/20year_freerun_output_NEWnci/outer_avg_*'))
ufiles = ufiles[start_id:end_id+1] # not sure what the +1 is doing here
vfiles = ufiles
tfiles = ufiles
bfiles = '/home/z5278054/EACouter_mesh_srho.nc' # For Hayden
mesh_mask = '/home/z5278054/EACouter_mesh_srho.nc' # For Hayden

# Set diffusion constants (in m/s)
Kh_zonal = 10
Kh_meridional = 10

filenames = {'U': ufiles,
             'V': vfiles,
             'temp': tfiles,
             'bathy': bfiles,
             'mesh_mask': mesh_mask}

variables = {'U': 'u',
             'V': 'v',
             'temp': 'temp',
             'bathy': 'h'}

out_file = str(out_dir)+'/'+str(year_array[array_ref])+'_Back.nc'


dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 's_rho', 'time': 'ocean_time'},
             'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 's_rho', 'time': 'ocean_time'},
             'temp': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 's_rho', 'time': 'ocean_time'},
             'bathy': {'lon': 'lon_rho', 'lat': 'lat_rho'}}

indices = {'depth': [29]}

if os.path.exists(out_file):
    os.remove(out_file)

def DeleteParticle(particle, fieldset, time):
    particle.delete()

fieldset = FieldSet.from_nemo(filenames, variables, dimensions, indices, allow_time_extrapolation=True)
fieldset.add_constant('maxage', 40.*86400)
fieldset.temp.interp_method = 'nearest'

# Create field of Kh_zonal and Kh_meridional, using same grid as U
size2D = (fieldset.U.grid.ydim, fieldset.U.grid.xdim)
fieldset.add_field(Field('Kh_zonal', Kh_zonal*np.ones(size2D), 
                         lon=fieldset.U.grid.lon, lat=fieldset.U.grid.lat, mesh='spherical'))
fieldset.add_field(Field('Kh_meridional', Kh_meridional*np.ones(size2D), 
                         lon=fieldset.U.grid.lon, lat=fieldset.U.grid.lat, mesh='spherical'))

random.seed(123456) # Set random seed

class SampleParticle(JITParticle): # Define a new particle class
    age = Variable('age', dtype=np.float32, initial=0.) # initialise age
    temp = Variable('temp', dtype=np.float32, initial=fieldset.temp)  # initialise temperature
    bathy = Variable('bathy', dtype=np.float32, initial=fieldset.bathy)  # initialise bathy
    distance = Variable('distance', initial=0., dtype=np.float32)  # the distance travelled
    prev_lon = Variable('prev_lon', dtype=np.float32, to_write=False,
                        initial=attrgetter('lon'))  # the previous longitude
    prev_lat = Variable('prev_lat', dtype=np.float32, to_write=False,
                        initial=attrgetter('lat'))  # the previous latitude.


def SampleDistance(particle, fieldset, time):
    # Calculate the distance in latitudinal direction (using 1.11e2 kilometer per degree latitude)
    lat_dist = (particle.lat - particle.prev_lat) * 1.11e2
    # Calculate the distance in longitudinal direction, using cosine(latitude) - spherical earth
    lon_dist = (particle.lon - particle.prev_lon) * 1.11e2 * math.cos(particle.lat * math.pi / 180)
    # Calculate the total Euclidean distance travelled by the particle
    particle.distance += math.sqrt(math.pow(lon_dist, 2) + math.pow(lat_dist, 2))
    particle.prev_lon = particle.lon  # Set the stored values for next iteration.
    particle.prev_lat = particle.lat
    
def SampleAge(particle, fieldset, time):
    particle.age = particle.age + math.fabs(particle.dt)
    if particle.age > fieldset.maxage:
        particle.delete()

def SampleTemp(particle, fieldset, time):
    particle.temp = fieldset.temp[time, particle.depth, particle.lat, particle.lon]

def SampleBathy(particle, fieldset, time):
    particle.bathy = fieldset.bathy[0, 0, particle.lat, particle.lon]

end_time = np.repeat(end_time,len(lon))

pset = ParticleSet.from_list(fieldset, pclass=SampleParticle, lon=lon, lat=lat, time=end_time, repeatdt=repeatdt)

pfile = pset.ParticleFile(out_file, outputdt=delta(days=1))

kernels = pset.Kernel(AdvectionRK4) + SampleAge + SampleTemp + SampleBathy + SampleDistance + DiffusionUniformKh

pset.execute(kernels, 
             dt=-delta(minutes=5), 
             output_file=pfile, 
             verbose_progress=True,
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
			 endtime = start_time)
pfile.close()
```

Error
```
WARNING: Casting lon data to np.float32
WARNING: Casting lat data to np.float32
WARNING: Casting depth data to np.float32
WARNING: Trying to initialize a shared grid with different chunking sizes - action prohibited. Replacing requested field_chunksize with grid's master chunksize.
WARNING: Casting time data to np.float64
WARNING: Casting field data to np.float32
INFO: Compiled random ==> /scratch/pbs.497989.kman.restech.unsw.edu.au/parcels-15278054/parcels_random_83b14cd5-cf7f-4a3a-a1f9-39c45ff2a00b.so
Traceback (most recent call last):
  File "gmc_back_1994.py", line 139, in <module>
    pset = ParticleSet.from_list(fieldset, pclass=SampleParticle, lon=lon, lat=lat, time=end_time, repeatdt=repeatdt)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/particleset.py", line 342, in from_list
    return cls(fieldset=fieldset, pclass=pclass, lon=lon, lat=lat, depth=depth, time=time, repeatdt=repeatdt, lonlatdepth_dtype=lonlatdepth_dtype, **kwargs)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/particleset.py", line 278, in __init__
    v.initial.fieldset.computeTimeChunk(time[i], 0)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/fieldset.py", line 932, in computeTimeChunk
    data = f.computeTimeChunk(data, tind)
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py", line 1306, in computeTimeChunk
    buffer_data = filebuffer.data
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py", line 2114, in data
    return self.data_access()
  File "/home/z5278054/test_python_env/lib/python3.8/site-packages/parcels/field.py", line 2204, in data_access
    data = data.rechunk(self.chunk_mapping)
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 2201, in rechunk
    return rechunk(self, chunks, threshold, block_size_limit)
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/rechunk.py", line 233, in rechunk
    chunks = normalize_chunks(
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 2484, in normalize_chunks
    chunks = sum(
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 2486, in <genexpr>
    blockdims_from_blockshape((s,), (c,))
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 974, in blockdims_from_blockshape
    return tuple(
  File "/apps/python/3.8.3/lib/python3.8/site-packages/dask/array/core.py", line 975, in <genexpr>
    ((bd,) * (d // bd) + ((d % bd,) if d % bd else ()) if d else (0,))
ZeroDivisionError: integer division or modulo by zero
```

**Comment by erikvansebille** [comment]
Hmm, I have not seen this dask error before. You say it appears with the latest version of dask?

You can turn off dask by adding `field_chunksize=False` to your `FieldSet.from_nemo(...)` command. This will lead to higher memory usage, but if you have sufficient memory anyways, it could help circumvent the error?

**Comment by DEHewitt** [comment]
Thanks for your help, @erikvansebille. We're still working on this and will provide feedback once we have some (that is more complete). Thanks!

**Comment by HaydenSchilling** [comment]
Thanks @erikvansebille , I have an update on what @DEHewitt and myself have been attempting. Dan's original error which was repeated many times resulting in excessively large error files (filling up the HPC memory allocation):
```
Correct cell not found for (154.050926, -25.534158) after 1000000 iterations
Debug info: old particle indices: (yi, xi) 314 45
            new particle indices: (yi, xi) 314 226
            Mesh 2d shape:  316 271
            Relative particle position:  (xsi, eta) -6.1320155892265049e-01 1.0127507928492394e+00
```
occurs only on the HPC, it runs fine on my windows laptop (using a reduced dataset on both). This is using Parcels v2.2.0 with Python 3.6.5 (the HPC did not like the Python 3.8 with Parcels v2.2.0 so we went back to python 3.6)

Following your suggestion and editing the `itMax` value we attempted to use the development version and this resulted in the second error Dan reported. This error occurs with the development version before (and after) we attempt to edit anything.
```
ZeroDivisionError: integer division or modulo by zero
```

I then attempted to change the v2.2.0 and edited the `itMax` value in that version and it runs on both my windows laptop and the HPC but it does not track any particles so i think i did something a little wrong.
```
ParticleSet is empty on writing as array at time 2.4624e+06
```

 So i think there is something in the development version that did not like our code (possibly the nesting).

I also tried including and excluding the `field_chunksize=False` in the `FieldSet.from_nemo(...)` command and it did not change anything in the working 2.2.0 version of parcels.

We still get the original issue of the correct cell error occurs so many times it gets a massive error file. Do you have any further suggestions or can I provide more information?

**Comment by erikvansebille** [comment]
I've looked at your Issue again, and it maybe that your problem is a really fundamental one to how Parcels now does nesting. As all of the development/testing was done on RectilinearGrids, it was easy to see if a Particle was out of bounds in the inner grid, and then move it to the outer grid. However, if the inner grid is curvilinear, then Parcels first tries to do this iterative find of the grid cell, which is why you keep seeing these warning messages, for every particle that moves from the inner to the outer grid

I don't think I have an easy solution for this, I fear. Supporting nesting with Curvilinear Grids will require a major redevelopment of how we deal with nesting; for which we don't have time now here in Utrecht. Is there no other way you can get around this? Or would you want to try develop and contribute this feature yourself?

Sorry that I can't be more helpful at the moment

**Comment by HaydenSchilling** [comment]
Thanks @erikvansebille, I will have an attempt at finding a work around (I am encouraged by the fact it appears to run without this warning on my laptop) and a look at the nesting source code but rewriting it is probably beyond my python ability at the moment.

I will post some feedback here on our final solution/work around.

**Comment by DEHewitt** [comment]
Hi @erikvansebille, we have pivoted away and potentially arrived back at this issue. Unfortunately, developing the feature in Parcels is beyond my Python ability too. I am here hoping you can point me in the direction of any examples you're aware of that accomplish nesting using if/else statements depending on particle position, or using recovery kernels (as I note in the tutorial for nesting it says this is possible). Many thanks!

**Comment by erikvansebille** [comment]
Dear @DEHewitt. Sorry that it is proving so difficult to implement nesting for curvilinear grids. I'm not sure of any if/else solutions that you point to

Another option, depending on exactly your Field setup, is to interpolate the parent nest onto the child nest grid, and then not use nesting at all? This of course is far from an ideal solution (would require much more storage!) but might be easiest to get going?

**Comment by DEHewitt** [comment]
No worries @erikvansebille. I think I follow your second option and may be useful. There are other products in my region of interest that encompass the entire range of the species I'm interested in, just at a coarser resolution (but not too coarse). Thanks for your assistance so far!

**Comment by cgrimaldi** [comment]
Hi all
Just wondering if you found any solution for this? Never had this issue before running earlier versions of parcels on HPC but just updated python and ocean parcels to the latest version (3.0.3) on our HPC and has seem to break it. 
Same error: "Correct cell not found for (357084.625000, 8433760.000000) after 1000000 iterations
Debug info: old particle indices: (yi, xi) 0 63
            new particle indices: (yi, xi) 0 63
            Mesh 2d shape:  300 330"
Thanks for your help :)
Camille

**Comment by cgrimaldi** [comment]
Hi Erik
Thank you for your quick reply! Yes I do work with a fine-scale model referenced in UTM (m) and have the right mesh='flat' when I generate my fieldset. Any other suggestions?
Thank you again - I've tried everything and can't seem to figure this one out.
Camille
