### ISSUE TITLE
Issue with adding fields to a SummedField

### ISSUE THREAD

**Issue by VictorOnink** [OceanParcels/parcels#926]
I have come across an issue with adding new fields to a summed field. I create my fieldset as follows:
```
filenames = {'U': datadirec+"HYCOM/HYCOM*2000*.nc",
                 'V': datadirec+"HYCOM/HYCOM*2000*.nc",
                 'Ust': datadirec+"WaveWatchIIIstokes/ww3.2010*_uss.nc",
                 'Vst': datadirec+"WaveWatchIIIstokes/ww3.2010*_uss.nc",
                    }
    variables = {'U': 'water_u',
                 'V': 'water_v',
                 'Ust': 'uuss',
                 'Vst': 'vuss',
                    }
    dimensions = {'U':{'time': 'time','depth':'depth','lat': 'lat','lon': 'lon'},
                  'V':{'time': 'time','depth':'depth','lat': 'lat','lon': 'lon'},
                  'Ust':{'lat': 'latitude','lon': 'longitude','time': 'time'},
                  'Vst':{'lat': 'latitude','lon': 'longitude','time': 'time'},
                  }
    
    fieldset = FieldSet.from_netcdf(filenames, variables, dimensions,allow_time_extrapolation=True)
    
    ###########################################################################
    # Adding the Stokes drift to the HYCOM currents                           #
    ###########################################################################
    os.system('echo "Adding Stokes drift"')
    if stokes==0:
        fieldset.Ust.units = GeographicPolar()
        fieldset.Vst.units = Geographic()
        fieldset=FieldSet(U=fieldset.U+fieldset.Ust,
                          V=fieldset.V+fieldset.Vst,
                          )
```
So, fieldset is now a SummedField. I can add new fields to this, generally without issue, using the add_field command. For example, the following works without issue:
```
s=np.load(dataInputdirec+'coastline_sand_vs_not_sand.npy')
p_r=np.exp(-timedelta(minutes=10).total_seconds()/(ProbShore(shoreDepen,scenario,s)*86400.))        
fieldset.add_field(Field('p_resus', p_r,lon=lon_kh,lat=lat_kh,mesh='spherical'))
```
Problems arise when I want to add wind data, where this data is spread out over a number of datafiles. In a previous version of my code (running with parcels 2.0), the following piece of code worked without any issues:

```
windFiles = {'windU': datadirec+'Wind/ERA5-wind10m*20*.nc',
                     'windV': datadirec+'Wind/ERA5-wind10m*20*.nc'}
windVar = {'windU':'u10', 'windV':'v10'}
windDimen = { 'time':'time','lat': 'latitude','lon': 'longitude'}
fieldset_wnd=FieldSet.from_netcdf(windFiles,windVar,windDimen,allow_time_extrapolation=True)
fieldset.add_field(fieldset_wnd.windU)
fieldset.add_field(fieldset_wnd.windV)
```
However, I now get the following error:
```
Traceback (most recent call last):
  File "generalBeachingScenarios.py", line 77, in <module>
    fieldset=CreateFieldSet(server,stokes,scenario)
  File "/gpfs/homefs/climate/vo18e689/codes/Next-Stage-Plastic-Beaching/Model/setupFunc.py", line 424, in CreateFieldSet
    fieldset.add_field(fieldset_wnd.windU)
  File "/home/ubelix/climate/vo18e689/anaconda3/envs/py3_parcels_v2_2/lib/python3.6/site-packages/parcels/fieldset.py", line 150, in add_field
    if fld.grid == g_set:
AttributeError: 'SummedField' object has no attribute 'grid'
```
I have talked with Christian about this issue already and he has given me a temporary fix that I can use to get around this issue with my code, but I would like to point out this issue here so it can be resolved.

**Comment by erikvansebille** [comment]
Hi @VictorOnink; this seems to be the same bug as https://github.com/OceanParcels/parcels/issues/837. 

Even though that bug was fixed on 18 May, our last conda version was from a week before, so this is not yet in the conda. Working with the developer (`master`) branch should fix this.
